in_channels = 160
input_size_time = 2
in_channels_static = 8
input_scalers_epsilon = 0.0
static_input_scalers_epsilon = 0.0
n_lats_px = 360
n_lons_px = 576
patch_size_px = [2, 2]
mask_unit_size_px = [30, 32]
embed_dim = 2560
n_blocks_encoder = 12
n_blocks_decoder = 2
mlp_multiplier = 4
n_heads = 16
dropout = 0.0
drop_path = 0.0
parameter_dropout = 0.0
positional_encoding = "fourier"
encoder_shifting = true
decoder_shifting = true
